### ISSUE TITLE
Please change Maven groupId and packages

### ISSUE THREAD

**Issue by lukaseder** [dmitry-zhuravlev/jooq-postgis-spatial#1]
First off, thank you very much for your contribution. I've just found this on Google while looking into solving an issue related to jOOQ's code generation for PostGIS types: https://github.com/jOOQ/jOOQ/issues/5872

Unfortunately, I need to ask you to rename your work's namespaces. We own the domain `org.jooq` and registered the jOOQ trademark. Your usage of the `org.jooq` groupId Java package prefix is against our trademark policies, mostly because we do not want people to think that this third-party work is ours or that we endorse using it.

The easiest solution would be to rename things to your personal name.

Thank you very much for your understanding.

**Comment by lukaseder** [comment]
For example, this can be seen also in the other project you've linked from your readme:

- https://github.com/gquintana/jooq-mysql-spatial/blob/master/pom.xml#L4
- https://github.com/gquintana/jooq-mysql-spatial/blob/master/src/main/java/net/gquintana/jooq/mysql/GeometryConverter.java#L4

**Comment by dmitry-zhuravlev** [comment]
Ok, no problem. I'll change it. Thanks for note!
