### ISSUE TITLE
upgrade jts from com.vividsolutions.jts to org.locationtech.jts

### ISSUE THREAD

**Issue by oshai** [dmitry-zhuravlev/jooq-postgis-spatial#8]
Thanks for maintaining this repo! We are using it for more than a year now.
We are now migrating from legacy `com.vividsolutions.jts` to the new `org.locationtech.jts`.
Migration looks pretty straight forward: https://github.com/locationtech/jts/blob/master/MIGRATION.md
But it breaks backward compatibility.

I wanted to know if it's possible to also upgrade this project?
If you want I can create a PR.

**Comment by dmitry-zhuravlev** [comment]
Sure, lets upgrade. PR are welcome. Please create one, change readme in accordance and test if all work with the new version of JTS as expected.

**Comment by oshai** [comment]
Hi, did you had a chance to take a look on PR #9 ?

**Comment by dmitry-zhuravlev** [comment]
Thanks for contribution!

**Comment by oshai** [comment]
Thanks for merging the PR!
Do you plan to release a new version to maven central?
